### PR TITLE
user-agents aren't required headers in the http standard

### PR DESCRIPTION
**Pull request by firecow**
Fixing `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_agent' cannot be null`

### CODE REVIEW

**Comment by ghost** [comment]
It wouldn't be more appropriate to make a migration and making user_agent nullable?

**Review by moberghammer — APPROVED** [review]
LGTM

**Comment by firecow** [comment]
I agree with @LauJosefsenCego 
Are you ok with that @nizacegodk ?

**Comment by nizacegodk** [comment]
@firecow Jeg har ingen aktier i det - Det helt fint med mig. Tom string var bare den nemmeste løsning :smile:

**Pull request merged**
